// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalWebsite.Data;

#nullable disable

namespace PersonalWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418002744_Databasteknik")]
    partial class Databasteknik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalWebsite.Models.AboutMe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("text");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AboutMe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Driven och mångsidig professionell med erfarenhet inom kundservice och försäljning. Starka färdigheter i kassahantering och teamarbete, med en bakgrund som receptionist och butiksäljare. Utrustad med en utbildning inom systemutveckling och medieteknik, är jag engagerad i att skapa positiva kundupplevelser och effektivt hantera administrativa uppgifter.",
                            GithubUrl = "https://github.com/wcb2006",
                            LinkedInUrl = "https://www.linkedin.com/in/williamcborg/",
                            Name = "William Borg",
                            Title = "Systemutvecklare"
                        });
                });

            modelBuilder.Entity("PersonalWebsite.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("PersonalWebsite.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EducationId")
                        .HasColumnType("integer");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EducationId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Syntax för C#. Hur C# och .NET kan användas för att lösa olika typer av uppgifter. Versionshantering.",
                            EducationId = 1,
                            Grade = "VG",
                            Name = "Programmering med C#/.NET, grund",
                            StartDate = new DateTime(2025, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Utveckla färdigheter för att motivera sig själv samt attityder som leder till maximal utveckling under studietiden och i arbetslivet. Fokus på ökad anställningsbarhet.",
                            EducationId = 1,
                            Grade = "VG",
                            Name = "Självledarskap - att leda sig själv, grund",
                            StartDate = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modellering, lagring och hämtning av data i databaser. SQL, databasdesign och jämförelse av olika databassystem.",
                            EducationId = 1,
                            Grade = "VG",
                            Name = "Databasteknik",
                            StartDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PersonalWebsite.Models.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Systemutvecklare inriktning säkerhet",
                            School = "JENSEN yrkeshögskola",
                            StartYear = 2025
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Informations- och medieteknik, Teknikprogrammet",
                            EndYear = 2025,
                            School = "NTI Gymnasiet, Malmö",
                            StartYear = 2022
                        });
                });

            modelBuilder.Entity("PersonalWebsite.Models.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Pranari, Malmö",
                            Description = "Administrerade inkommande samtal och dirigerade dem effektivt. Mottog och välkomnade besökare för att skapa ett trevligt intryck.",
                            Role = "Receptionist",
                            StartDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Company = "Circle K, Malmö",
                            Description = "Hanterar kassan och genomför snabba och exakta transaktioner. Utbildar nya medarbetare i försäljningstekniker och kundservice. Skapar och bibehåller en inbjudande och säljande butiksmiljö.",
                            Role = "Butiksäljare",
                            StartDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Company = "Region Skåne, Malmö",
                            Description = "Databas- och registerhantering. Samordning med olika avdelningar. Hanterar datorer och tekniska system. Effektivt utförande av tilldelade uppgifter.",
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Vikarie",
                            StartDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Company = "Region Skåne, Malmö",
                            Description = "Effektivt utförande av tilldelade uppgifter.",
                            EndDate = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Sommarpraktikant",
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Company = "Malmö Museum & Tekniska Museum, Malmö",
                            Description = "Effektivt utförande av tilldelade uppgifter. Samordnade arbetslag.",
                            EndDate = new DateTime(2023, 8, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Sommarpraktikant",
                            StartDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Company = "Pranari, Malmö",
                            Description = "Administrerade inkommande samtal och dirigerade dem effektivt. Mottog och välkomnade besökare för att skapa ett trevligt intryck.",
                            EndDate = new DateTime(2021, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Role = "Receptionist",
                            StartDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PersonalWebsite.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProjectUrl")
                        .HasColumnType("text");

                    b.Property<string>("Technologies")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "En personlig hemsida byggd med ASP.NET Core MVC och PostgreSQL.",
                            Technologies = "C#, ASP.NET Core, PostgreSQL, Bootstrap",
                            Title = "Personlig hemsida",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("PersonalWebsite.Models.Course", b =>
                {
                    b.HasOne("PersonalWebsite.Models.Education", "Education")
                        .WithMany("Courses")
                        .HasForeignKey("EducationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Education");
                });

            modelBuilder.Entity("PersonalWebsite.Models.Education", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
